// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finalProject_wsad_bradyk4.Models;

namespace finalProject_wsad_bradyk4.Migrations
{
    [DbContext(typeof(MedalContext))]
    [Migration("20211206015147_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("finalProject_wsad_bradyk4.Models.Medal", b =>
                {
                    b.Property<int>("MedalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Place")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MedalId");

                    b.ToTable("Medals");

                    b.HasData(
                        new
                        {
                            MedalId = 1,
                            Event = "US University Nationals",
                            Name = "Jordan Burroughs",
                            Place = 2,
                            Year = 2007
                        },
                        new
                        {
                            MedalId = 2,
                            Event = "US Open",
                            Name = "Jordan Burroughs",
                            Place = 1,
                            Year = 2011
                        },
                        new
                        {
                            MedalId = 3,
                            Event = "World Championships",
                            Name = "Jordan Burroughs",
                            Place = 1,
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
